version: '{build}'
branches:
  only:
  - master
  - develop
os: Visual Studio 2015
configuration: Release
platform: Any CPU
init:
- cmd: >-
    pushd %VS140COMNTOOLS%
    VsMSBuildCmd.bat
    popd
    wget "http://www.sato.co.jp/download/manual/LespritV-v12_0_0_50-64bit.zip"
    7z x LespritV-v12_0_0_50-64bit.zip
    cd LespritV-v12_0_0_50-64bit\LespritV-v12_0_0_50-64bit\LespritV\Driver64
    rundll32 printui.dll PrintUIEntry /if /f LES400V.INF /r USB001 /m "SATO Lesprit408v" /v 2 /b T408v
nuget:
  disable_publish_on_pr: true
before_build:
- cmd: nuget restore TinySato.sln
build:
  project: TinySato.sln
  publish_nuget: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: 1+Nth2VKA73r0Go+t1YR8JA9WH7Kc0OELQvVsMh0xL3VAxXZcgQjMpX91gwPrOTK
  artifact: /TinySato.*\.nupkg/
artifacts:
  - path: TinySato/bin/Releases/TinySato.dll
    name: TinySato
