os: Visual Studio 2019
configuration: Release
platform: Any CPU
build:
  project: TinySato.sln
  publish_nuget: true
  verbosity: minimal
artifacts:
  - path: TinySato\bin\Release\TinySato.dll
    name: TinySato

deploy:
  release: tinysato-v$(appveyor_build_version)
  description: 'Release by appveyor'
  provider: GitHub
  auth_token:
    secure: 51CWzgazGObQuECwxcfMhogo5L/2k9Eu3sn9aWx6tS/YYg/Sz3egOG7LRYspPS1m
  artifact: /.*\.nupkg/
  draft: true
  prerelease: true
...
